### ISSUE TITLE
Error with running Accel-Sim SASS Frontend and Simulation Engine

### ISSUE THREAD

**Issue by wangyuyue** [accel-sim/accel-sim-framework#165]
Dear developers,
I ran into the following error when run the command `./util/job_launching/run_simulations.py -B rodinia_2.0-ft -C TITANX -T ./hw_run/traces/device-0/11.0/ -N 0`.

```
glacier@node0:~/work/accel-sim-framework$ ./util/job_launching/run_simulations.py -B rodinia_2.0-ft -C TITANX -T ./hw_run/traces/device-0/11.0/ -N 0
Cannot find a supported job management system. Spawning jobs locally.
Running Simulations with GPGPU-Sim built from 
accelsim-commit-2260456ea5e6a1420f5734f145a4b7d8ab1d4737_modified_0.0
 
Using configs: TITANX
Benchmark: rodinia_2.0-ft
Run Subdir = TITANX
Parameters = 
Base config file = /users/glacier/work/accel-sim-framework/gpu-simulator/gpgpu-sim/configs/tested-cfgs/SM6_TITANX/gpgpusim.config
Traceback (most recent call last):
  File "/users/glacier/work/accel-sim-framework/util/job_launching/procman.py", line 513, in <module>
    main()
  File "/users/glacier/work/accel-sim-framework/util/job_launching/procman.py", line 492, in main
    procMan.saveState()
  File "/users/glacier/work/accel-sim-framework/util/job_launching/procman.py", line 146, in saveState
    pickle.dump(self, open(self.pickleFile, "wb+"))
FileNotFoundError: [Errno 2] No such file or directory: '/users/glacier/accel-sim-framework/util/job_launching/procman/procman.node0.tmp--gpu.nestfarm-pg0.wisc.cloudlab.us.pickle'
Job  queued (backprop-rodinia-2.0-ft-4096___data_result_4096_txt TITANX)
Traceback (most recent call last):
  File "/users/glacier/work/accel-sim-framework/util/job_launching/procman.py", line 513, in <module>
    main()
  File "/users/glacier/work/accel-sim-framework/util/job_launching/procman.py", line 492, in main
    procMan.saveState()
  File "/users/glacier/work/accel-sim-framework/util/job_launching/procman.py", line 146, in saveState
    pickle.dump(self, open(self.pickleFile, "wb+"))
FileNotFoundError: [Errno 2] No such file or directory: '/users/glacier/accel-sim-framework/util/job_launching/procman/procman.node0.tmp--gpu.nestfarm-pg0.wisc.cloudlab.us.pickle'
Job  queued (bfs-rodinia-2.0-ft-__data_graph4096_txt___data_graph4096_result_txt TITANX)
Traceback (most recent call last):
  File "/users/glacier/work/accel-sim-framework/util/job_launching/procman.py", line 513, in <module>
    main()
  File "/users/glacier/work/accel-sim-framework/util/job_launching/procman.py", line 492, in main
    procMan.saveState()
  File "/users/glacier/work/accel-sim-framework/util/job_launching/procman.py", line 146, in saveState
    pickle.dump(self, open(self.pickleFile, "wb+"))
FileNotFoundError: [Errno 2] No such file or directory: '/users/glacier/accel-sim-framework/util/job_launching/procman/procman.node0.tmp--gpu.nestfarm-pg0.wisc.cloudlab.us.pickle'
Job  queued (hotspot-rodinia-2.0-ft-30_6_40___data_result_30_6_40_txt TITANX)
Traceback (most recent call last):
  File "/users/glacier/work/accel-sim-framework/util/job_launching/procman.py", line 513, in <module>
    main()
  File "/users/glacier/work/accel-sim-framework/util/job_launching/procman.py", line 492, in main
    procMan.saveState()
  File "/users/glacier/work/accel-sim-framework/util/job_launching/procman.py", line 146, in saveState
    pickle.dump(self, open(self.pickleFile, "wb+"))
FileNotFoundError: [Errno 2] No such file or directory: '/users/glacier/accel-sim-framework/util/job_launching/procman/procman.node0.tmp--gpu.nestfarm-pg0.wisc.cloudlab.us.pickle'
Job  queued (heartwall-rodinia-2.0-ft-__data_test_avi_1___data_result_1_txt TITANX)
Traceback (most recent call last):
  File "/users/glacier/work/accel-sim-framework/util/job_launching/procman.py", line 513, in <module>
    main()
  File "/users/glacier/work/accel-sim-framework/util/job_launching/procman.py", line 492, in main
    procMan.saveState()
  File "/users/glacier/work/accel-sim-framework/util/job_launching/procman.py", line 146, in saveState
    pickle.dump(self, open(self.pickleFile, "wb+"))
FileNotFoundError: [Errno 2] No such file or directory: '/users/glacier/accel-sim-framework/util/job_launching/procman/procman.node0.tmp--gpu.nestfarm-pg0.wisc.cloudlab.us.pickle'
Job  queued (lud-rodinia-2.0-ft-_v__b__i___data_64_dat TITANX)
Traceback (most recent call last):
  File "/users/glacier/work/accel-sim-framework/util/job_launching/procman.py", line 513, in <module>
    main()
  File "/users/glacier/work/accel-sim-framework/util/job_launching/procman.py", line 492, in main
    procMan.saveState()
  File "/users/glacier/work/accel-sim-framework/util/job_launching/procman.py", line 146, in saveState
    pickle.dump(self, open(self.pickleFile, "wb+"))
FileNotFoundError: [Errno 2] No such file or directory: '/users/glacier/accel-sim-framework/util/job_launching/procman/procman.node0.tmp--gpu.nestfarm-pg0.wisc.cloudlab.us.pickle'
Job  queued (nw-rodinia-2.0-ft-128_10___data_result_128_10_txt TITANX)
Traceback (most recent call last):
  File "/users/glacier/work/accel-sim-framework/util/job_launching/procman.py", line 513, in <module>
    main()
  File "/users/glacier/work/accel-sim-framework/util/job_launching/procman.py", line 492, in main
    procMan.saveState()
  File "/users/glacier/work/accel-sim-framework/util/job_launching/procman.py", line 146, in saveState
    pickle.dump(self, open(self.pickleFile, "wb+"))
FileNotFoundError: [Errno 2] No such file or directory: '/users/glacier/accel-sim-framework/util/job_launching/procman/procman.node0.tmp--gpu.nestfarm-pg0.wisc.cloudlab.us.pickle'
Job  queued (nn-rodinia-2.0-ft-__data_filelist_4_3_30_90___data_filelist_4_3_30_90_result_txt TITANX)
Traceback (most recent call last):
  File "/users/glacier/work/accel-sim-framework/util/job_launching/procman.py", line 513, in <module>
    main()
  File "/users/glacier/work/accel-sim-framework/util/job_launching/procman.py", line 492, in main
    procMan.saveState()
  File "/users/glacier/work/accel-sim-framework/util/job_launching/procman.py", line 146, in saveState
    pickle.dump(self, open(self.pickleFile, "wb+"))
FileNotFoundError: [Errno 2] No such file or directory: '/users/glacier/accel-sim-framework/util/job_launching/procman/procman.node0.tmp--gpu.nestfarm-pg0.wisc.cloudlab.us.pickle'
Job  queued (pathfinder-rodinia-2.0-ft-1000_20_5___data_result_1000_20_5_txt TITANX)
Traceback (most recent call last):
  File "/users/glacier/work/accel-sim-framework/util/job_launching/procman.py", line 513, in <module>
    main()
  File "/users/glacier/work/accel-sim-framework/util/job_launching/procman.py", line 492, in main
    procMan.saveState()
  File "/users/glacier/work/accel-sim-framework/util/job_launching/procman.py", line 146, in saveState
    pickle.dump(self, open(self.pickleFile, "wb+"))
FileNotFoundError: [Errno 2] No such file or directory: '/users/glacier/accel-sim-framework/util/job_launching/procman/procman.node0.tmp--gpu.nestfarm-pg0.wisc.cloudlab.us.pickle'
Job  queued (srad_v2-rodinia-2.0-ft-__data_matrix128x128_txt_0_127_0_127__5_2___data_result_matrix128x128_1_150_1_100__5_2_txt TITANX)
Traceback (most recent call last):
  File "/users/glacier/work/accel-sim-framework/util/job_launching/procman.py", line 513, in <module>
    main()
  File "/users/glacier/work/accel-sim-framework/util/job_launching/procman.py", line 492, in main
    procMan.saveState()
  File "/users/glacier/work/accel-sim-framework/util/job_launching/procman.py", line 146, in saveState
    pickle.dump(self, open(self.pickleFile, "wb+"))
FileNotFoundError: [Errno 2] No such file or directory: '/users/glacier/accel-sim-framework/util/job_launching/procman/procman.node0.tmp--gpu.nestfarm-pg0.wisc.cloudlab.us.pickle'
Job  queued (streamcluster-rodinia-2.0-ft-3_6_16_1024_1024_100_none_output_txt_1___data_result_3_6_16_1024_1024_100_none_1_txt TITANX)
Traceback (most recent call last):
  File "/users/glacier/work/accel-sim-framework/util/job_launching/procman.py", line 513, in <module>
    main()
  File "/users/glacier/work/accel-sim-framework/util/job_launching/procman.py", line 446, in main
    procMan.spawnProcMan(options.sleepTime)
  File "/users/glacier/work/accel-sim-framework/util/job_launching/procman.py", line 174, in spawnProcMan
    shutil.copy(self.pickleFile, self.pickleFile + ".tmp")
  File "/usr/lib/python3.8/shutil.py", line 415, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.8/shutil.py", line 261, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: '/users/glacier/accel-sim-framework/util/job_launching/procman/procman.node0.tmp--gpu.nestfarm-pg0.wisc.cloudlab.us.pickle'
```

Yesterday, the first time I run it, it succeeded. I have no idea what's wrong now. Please help me, thanks.

**Comment by JRPan** [comment]
Can you try delete the `/util/jon_launching/procman` and the `/util/jon_launching/procman/logfiles` folder to see if that helps?

The is just a script we use to manage the jobs. Deleting the folders should reset it.

Thanks,
JR

**Comment by wangyuyue** [comment]
Thanks, it solved the problem.

And could you provide a table of application name correspondence? I notice that the application name changes in different steps, like building the application binary, running the application with instruments,s and feeding the trace into accel-sim. For example, `./util/tracer_nvbit/run_hw_trace.py -B cutlass  -D 0` returns the error:
```
Traceback (most recent call last):
  File "./util/tracer_nvbit/run_hw_trace.py", line 41, in <module>
    benchmarks = common.gen_apps_from_suite_list(options.benchmark_list.split(","))
  File "/users/glacier/work/accel-sim-framework/util/tracer_nvbit/../job_launching/common.py", line 118, in gen_apps_from_suite_list
    benchmarks += defined_apps[app]
KeyError: 'cutlass'
```

That would be greatly helpful.

**Comment by JRPan** [comment]
list of apps can be found here
https://github.com/accel-sim/accel-sim-framework/blob/release/util/job_launching/apps/define-all-apps.yml
