### ISSUE TITLE
Correct RTX2060 config file

### ISSUE THREAD

**Issue by mahmoodn** [accel-sim/accel-sim-framework#7]
I have created some trace files for the `~/gpu-app-collection-release/bin/10.1/release/cfd-rodinia-3.1` application and the traces (used a 2080Ti device) are stored in

```
$ ls hw_run/traces/device-0/10.1/cfd-rodinia-3.1/_GPUAPPS_ROOT_data_dirs_cuda_rodinia_3_1_cfd_rodinia_3_1_data_missile_domn_0_2M/traces/
kernel-1000.trace  kernel-207.trace  kernel-340.trace  kernel-474.trace  kernel-607.trace  kernel-740.trace  kernel-874.trace
kernel-1001.trace  kernel-208.trace  kernel-341.trace  kernel-475.trace  kernel-608.trace  kernel-741.trace  kernel-875.trace
kernel-1002.trace  kernel-209.trace  kernel-342.trace  kernel-476.trace  kernel-609.trace  kernel-742.trace  kernel-876.trace
...
...
```
Now, I see that the following command fails:

```
$ ./util/job_launching/run_simulations.py -B mahmood -C RTX2060 -T ./hw_run/traces/device-0/10.1/ -N cfd-rodinia-3.1
Running Simulations with GPGPU-Sim built from
accelsim-commit-21fdb684796bba6057a45eeb6429b04cc7577537_modified_1.0

Using configs: RTX2060
Benchmark: mahmood
Run Subdir = RTX2060
Parameters =
Base config file = /home/mahmood/accel-sim-framework/gpu-simulator/gpgpu-sim/configs/tested-cfgs/Turing_RTX2060/gpgpusim.config
Traceback (most recent call last):
  File "./util/job_launching/run_simulations.py", line 363, in <module>
    config.run(version_string, benchmarks, options.run_directory, cuda_version, options.simulator_dir)
  File "./util/job_launching/run_simulations.py", line 76, in run
    self.append_gpgpusim_config(benchmark, this_run_dir, self.config_file)
  File "./util/job_launching/run_simulations.py", line 266, in append_gpgpusim_config
    config_text = open(config_text_file).read()
IOError: [Errno 2] No such file or directory: '/home/mahmood/accel-sim-framework/gpu-simulator/gpgpu-sim/configs/tested-cfgs/Turing_RTX2060/gpgpusim.config'
```
In fact there is no `Turing_RTX2060` in the config folders:
```
$ ls /home/mahmood/accel-sim-framework/gpu-simulator/gpgpu-sim/configs/tested-cfgs/
SM2_GTX480/       SM3_KEPLER_TITAN/ SM6_TITANX/       SM75_RTX2060/     SM7_QV100/        SM7_TITANV/
```
As you can see it is `SM75_RTX2060`. However, if I use `-C SM75_RTX2060`, I get this error
```
Could not fined SM75_RTX2060 in defined basenames {'QV100_SASS': '/home/mahmood/accel-sim-framework/gpu-simulator/gpgpu-sim/configs/tested-cfgs/SM7_QV100_SASS/gpgpusim.config', 'TESLAC2050': '/home/mahmood/accel-sim-framework/gpu-simulator/gpgpu-sim/configs/4.x-cfgs/SM2_C2050/gpgpusim.config', 'PUB_GTX480': '/home/mahmood/accel-sim-framework/gpu-simulator/gpgpu-sim/configs/GTX480/gpgpusim.config', 'TITANXX': '/home/mahmood/accel-sim-framework/gpu-simulator/gpgpu-sim/configs/tested-cfgs/TITANX-pascal/gpgpusim.config', 'GTX480': '/home/mahmood/accel-sim-framework/gpu-simulator/gpgpu-sim/configs/tested-cfgs/SM2_GTX480/gpgpusim.config', 'QV100': '/home/mahmood/accel-sim-framework/gpu-simulator/gpgpu-sim/configs/tested-cfgs/SM7_QV100/gpgpusim.config', 'QUADROFX5800': '/home/mahmood/accel-sim-framework/gpu-simulator/gpgpu-sim/configs/4.x-cfgs/SM1_QFX5800/gpgpusim.config', 'TITANK': '/home/mahmood/accel-sim-framework/gpu-simulator/gpgpu-sim/configs/tested-cfgs/SM3_KEPLER_TITAN/gpgpusim.config', 'RTX2060': '/home/mahmood/accel-sim-framework/gpu-simulator/gpgpu-sim/configs/tested-cfgs/Turing_RTX2060/gpgpusim.config', 'PUB_TITANX': '/home/mahmood/accel-sim-framework/gpu-simulator/gpgpu-sim/configs/SM6_TITANX/gpgpusim.config', 'QUADROFX5600': '/home/mahmood/accel-sim-framework/gpu-simulator/gpgpu-sim/configs/4.x-cfgs/SM1_QFX5600/gpgpusim.config', 'TITANX': '/home/mahmood/accel-sim-framework/gpu-simulator/gpgpu-sim/configs/tested-cfgs/SM6_TITANX/gpgpusim.config', 'PUB_GTX750': '/home/mahmood/accel-sim-framework/gpu-simulator/gpgpu-sim/configs/GeForceGTX750Ti/gpgpusim.config', 'QV100_old': '/home/mahmood/accel-sim-framework/gpu-simulator/gpgpu-sim/configs/tested-cfgs/SM7_QV100_old/gpgpusim.config', 'TITANV': '/home/mahmood/accel-sim-framework/gpu-simulator/gpgpu-sim/configs/tested-cfgs/SM7_TITANV/gpgpusim.config', 'PUB_GTX1080': '/home/mahmood/accel-sim-framework/gpu-simulator/gpgpu-sim/configs/GeForceGTX1080Ti/gpgpusim.config', 'TITANV_OLD': '/home/mahmood/accel-sim-framework/gpu-simulator/gpgpu-sim/configs/tested-cfgs/SM7_TITANV_OLD/gpgpusim.config', 'QV100_64SM': '/home/mahmood/accel-sim-framework/gpu-simulator/gpgpu-sim/configs/tested-cfgs/SM7_QV100_SMs/gpgpusim.config'}
```
It seems that there is a name inconsistency issue here. I would like to know which part of the scripts need modification before messing up things by myself.
Thanks for your attention.

**Comment by mkhairy** [comment]
Hi,

This seems to be a bug, to fix it quickly for you,  replace the turning line in the config file to:
 (what I did is to replace "Turing_RTX2060" to "SM75_RTX2060" in the directory)

```
#Turing
RTX2060:
    base_file: "$GPGPUSIM_ROOT/configs/tested-cfgs/SM75_RTX2060/gpgpusim.config"
```

then run it using your inital command line:
```
$ ./util/job_launching/run_simulations.py -B mahmood -C RTX2060 -T ./hw_run/traces/device-0/10.1/ -N cfd-rodinia-3.1
```

**Comment by mahmoodn** [comment]
Thank you. I will create a pull request.

**Comment by mahmoodn** [comment]
Pull request created:
https://github.com/accel-sim/accel-sim-framework/pull/9
