### ISSUE TITLE
Job queued with "-l local" option

### ISSUE THREAD

**Issue by mahmoodn** [accel-sim/accel-sim-framework#8]
Hi
My simple run on a local machine quickly ends with this output
```
$ ./util/job_launching/run_simulations.py -B mahmood -C RTX2060 -T ./hw_run/traces/device-0/10.1/ -N cfd-rodinia-3.1 -l local
Running Simulations with GPGPU-Sim built from
accelsim-commit-21fdb684796bba6057a45eeb6429b04cc7577537_modified_1.0

Using configs: RTX2060
Benchmark: mahmood
Run Subdir = RTX2060
Parameters =
Base config file = /home/mahmood/accel-sim-framework/gpu-simulator/gpgpu-sim/configs/tested-cfgs/SM75_RTX2060/gpgpusim.config
Job 3 queued (cfd-rodinia-3.1-_GPUAPPS_ROOT_data_dirs_cuda_rodinia_3_1_cfd_rodinia_3_1_data_missile_domn_0_2M RTX2060)
ProcMan spawned [pid=74837]
```
In fact there is no PID=74837 and the job monitor shows nothing until I press ^C.
```
$ ./util/job_launching/monitor_func_test.py -v -N cfd-rodinia-3.1
Calling job_status.py

^CTraceback (most recent call last):
  File "./util/job_launching/monitor_func_test.py", line 124, in <module>
    stdout=jobstatus_out_file, stderr=jobstatus_out_file) != 0:
  File "/usr/lib/python2.7/subprocess.py", line 172, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 1099, in wait
    pid, sts = _eintr_retry_call(os.waitpid, self.pid, 0)
  File "/usr/lib/python2.7/subprocess.py", line 125, in _eintr_retry_call
    return func(*args)
KeyboardInterrupt
```
I also see this log file which has nothing useful
```
$ cat util/job_launching/logfiles/sim_log.cfd-rodinia-3.1.20.09.08-Tuesday.txt
15:46:14      3 cfd-rodinia-3.1        _GPUAPPS_ROOT_data_dirs_cuda_rodinia_3_1_cfd_rodinia_3_1_data_missile_domn_0_2M                      RTX2060                   cfd-rodinia-3.1.accelsim-commit-21fdb684796bba6057a45eeb6429b04cc7577537_modified_1.0
```
Indeed trace files exist as you can see below:
```
$ ls hw_run/traces/device-0/10.1/cfd-rodinia-3.1/_GPUAPPS_ROOT_data_dirs_cuda_rodinia_3_1_cfd_rodinia_3_1_data_missile_domn_0_2M/traces/kernel-1.trace  -l
-rw-r--r-- 1 mahmood mahmood 10532923 Sep  7 16:41 hw_run/traces/device-0/10.1/cfd-rodinia-3.1/_GPUAPPS_ROOT_data_dirs_cuda_rodinia_3_1_cfd_rodinia_3_1_data_missile_domn_0_2M/traces/kernel-1.trace
```
So, any idea for more debugging?

**Comment by mahmoodn** [comment]
@mkhairy 
Can you please explain what is the normal output for run_simulations.py with local option? It is really weird that I don't see any running process.

**Comment by mahmoodn** [comment]
I guess I found for hints. As you can see below, the absolute path of `procman.py -S` works  instead of relative path.
```
$ /home/mahmood/accel-sim-framework/util/job_launching/procman.py -S     ProcMan spawned [pid=43921]
$ ./util/job_launching/procman.py -S
Traceback (most recent call last):
  File "./util/job_launching/procman.py", line 495, in <module>
    main()
  File "./util/job_launching/procman.py", line 428, in main
    procMan.spawnProcMan(options.sleepTime)
  File "./util/job_launching/procman.py", line 167, in spawnProcMan
    cwd=this_directory
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

Moreover, I found that `procman.py -p` better prints the information about the spawned job and its log paths.

```
$ ./util/job_launching/procman.py -p
Procman: procman.threadripper.pickle.tmp.43896
queuedJobs=0, activeJobs=0, completeJobs=1

queuedJobs:

activeJobs:

completeJobs:
        status=COMPLETE_NO_OTHER_INFO: [name=cfd-rodinia-3.1-_GPUAPPS_ROOT_data_dirs_cuda_rodinia_3_1_cfd_r      odinia_3_1_data_missile_domn_0_2M.accelsim-commit-d6f08e17f2fe1cf9ccbcbcb3f0d8fb09ca8b1fba_modified_1.0,pro      cId=43897,maxVmSize=0,runningTime=0,outF=/tmp/cfd-rodinia-3.1-_GPUAPPS_ROOT_data_dirs_cuda_rodinia_3_1_cfd_      rodinia_3_1_data_missile_domn_0_2M.accelsim-commit-d6f08e17f2fe1cf9ccbcbcb3f0d8fb09ca8b1fba_modified_1.0.o2      ,errF=/tmp/cfd-rodinia-3.1-_GPUAPPS_ROOT_data_dirs_cuda_rodinia_3_1_cfd_rodinia_3_1_data_missile_domn_0_2M.      accelsim-commit-d6f08e17f2fe1cf9ccbcbcb3f0d8fb09ca8b1fba_modified_1.0.e2,workingDir=/home/mahmood/accel-sim      -framework/sim_run_10.1/cfd-rodinia-3.1/_GPUAPPS_ROOT_data_dirs_cuda_rodinia_3_1_cfd_rodinia_3_1_data_missi      le_domn_0_2M/RTX2060,command=/home/mahmood/accel-sim-framework/util/job_launching/../../sim_run_10.1/cfd-ro      dinia-3.1/_GPUAPPS_ROOT_data_dirs_cuda_rodinia_3_1_cfd_rodinia_3_1_data_missile_domn_0_2M/RTX2060/slurm.sim      ]

Total Procmans=1, Total Queued=0, Total Running=0, Total Complete=1
```

As this `-p` option is missing in the second item of the **Accel-Sim Components** item, **Accel-Sim SASS Frontend**, I think new users may get confused. My recommendation is to mention that in the docs. Thanks.

**Comment by mkhairy** [comment]
Hello Mahmood, sorry for my late reply. I see your traces file have the extension ".trace" not ".traceg".
you need to run the post-traces-processing executable to the traces files.
Please, read the readme of tracer for the detailed steps"
https://github.com/accel-sim/accel-sim-framework/tree/release/util/tracer_nvbit

**Comment by mkhairy** [comment]
Thanks for your note. I cced @tgrogers for your comment.

**Comment by mahmoodn** [comment]
Right. I also found the error message in the `sim_run_10.1/cfd-rodinia-3.1/_GPUAPPS_ROOT_data_dirs_cuda_rodinia_3_1_cfd_rodinia_3_1_data_missile_domn_0_2M/RTX2060/` path:
```
*** Initializing Memory Statistics ***
GPGPU-Sim uArch: performance model initialization complete.
Unable to open file: ./traces/kernelslist.g
```
Following your reply, I see this command in the link you mentioned: `./tracer_tool/traces-processing/post-traces-processing ./traces/kernelslist`. I would like to add some notes about that. I think it should mention:
```
$ cd ~/accel-sim-framework/util/tracer_nvbit/tracer_tool/
$ make
g++ -o post-traces-processing post-traces-processing.cpp
$ cd ~/accel-sim-framework/hw_run/traces/device-0/10.1/cfd-rodinia-3.1/_GPUAPPS_ROOT_data_dirs_cuda_rodinia_3_1_cfd_rodinia_3_1_data_missile_domn_0_2M/traces/
$ ~/accel-sim-framework/util/tracer_nvbit/tracer_tool/traces-processing/post-traces-processing traces/kernelslist
Processing file traces/kernel-1.trace
Processing file traces/kernel-2.trace
Processing file traces/kernel-3.trace
...
```
I mean the user have to first make the post-trace-processing binary and that command must be run in the traces/ which contains `data  run.sh  traces/`

**Comment by mahmoodn** [comment]
One more thing. What is this Example?
```
Example:
./accelsim.out -trace ../../../../../../Nvbits/nvbit_1.1/nvbit_release/traces/kernelslist.g 
```
Is that something that I must run after post-trace-processing?
